package frc.robot.subsystems;

import com.ctre.phoenix.motorcontrol.can.VictorSPX;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

public class Drive extends SubsystemBase{
private  VictorSPX left1;
private  VictorSPX left2;

private  VictorSPX right1;
private  VictorSPX right2;

private SpeedControllerGroup leftMotor;


private DifferentialDrive drive;

    public Drive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
left1 = new VictorSPX(0);
 left1.setInverted(true);

left2 = new VictorSPX(1);
left2.setInverted(false);
left2.follow(left1);



right1 = new VictorSPX(2);
right1.setInverted(true);

right2 = new VictorSPX(3);
right2.setInverted(false);

right2.follow(right1);



drive = new DifferentialDrive(left1, right1);

}

    @Override
    public void periodic() {

    }

    @Override
    public void simulationPeriodic() {

    }


    public void drive(double xSpeed, double rotation, boolean inPlace){
        drive.curvatureDrive(xSpeed, rotation, inPlace);
    }

    
}
