package frc.robot.subsystems;

import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

public class Drive extends SubsystemBase{
private  WPI_VictorSPX left1;
private  WPI_VictorSPX left2;

private  WPI_VictorSPX right1;
private  WPI_VictorSPX right2;



private DifferentialDrive drive;

    public Drive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
left1 = new WPI_VictorSPX(0);
 left1.setInverted(false);

left2 = new WPI_VictorSPX(1);
left2.setInverted(false);
left2.follow(left1);



right1 = new WPI_VictorSPX(2);
right1.setInverted(true);

right2 = new WPI_VictorSPX(3);
right2.setInverted(true);

right2.follow(right1);



drive = new DifferentialDrive(left1, right1);

}

    @Override
    public void periodic() {

    }

    @Override
    public void simulationPeriodic() {

    }


    public void drive(double xSpeed, double rotation, boolean inPlace){
        drive.curvatureDrive(xSpeed, rotation, inPlace);
    }

    
}
